env:
  browser: true
  node: true
  commonjs: true
  es6: true
  mocha: true

parser: babel-eslint

parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module

extends:
- izumin5210
- izumin5210/react

settings:
  import/resolver:
    node:
      moduleDirectory:
      - node_modules
