env:
  browser: true
  node: true
  commonjs: true
  es6: true
  mocha: true

parser: babel-eslint

parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module

plugins:
- flowtype-errors

extends:
- izumin5210
- izumin5210/react
- izumin5210/flow

settings:
  import/resolver:
    node:
      moduleDirectory:
      - node_modules

globals:
  React: true
  assert: true

rules:
  flowtype-errors/show-errors: error
