language: node_js

node_js:
- 6

sudo: false

matrix:
  fast_finish: true
  include:
  # - os: osx
  #   osx_image: xcode8.2
  - os: linux
    dist: trusty

cache:
  yarn: true
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"

script:
- yarn test
- yarn build

notifications:
  slack:
    secure: XEpDeNPwlurfm7PAef1OzS+kCUIjF2In6WpoLL/1y/LN1uvQR0L8G+vRCbx4Fs3YgfN0+lDiOU/AwqFEvRmHPYalCb8iyupH7I1SxRWAGvDJdXVbslGu5WXI1NJan8zBrxVYTMEdZ8GglDWpd7oBymdP8TspoKABvKFDcgJZmoPcMBv07T+QhXzgUweDGlsmHv5CqoH0JwAHO2NBpEpe9hJo9G7n3U5+wEE7SU4FoOme8vgHkj28CLclyzwEPq5/+FMepNC5MA1NBf8fJoTCkCaytucjijfN4CQlHL1Bu9o9far8PX2AUhga2W+lM+tuzQc4SW3sMu/MwYVK0LHT+Xgk3L9WBZim4ZQykBrRCoBNvC6oVPVXPSnvO3Fo9PSBXvlXeqpgZmoj+C7tXo41Y+PqpDg6X/Y57+aTKAkQLPoD+kMHTsiPzHlkPCYEhptUq2ozmGhd5jv1MsYxTtv4KQ2Mbz1gHTd9T1rLs3BonuULGtqQvT+d8Gy2ShDAJD0e5tldkmxvzB/LzA116rIXzmmBJJeU5K0kc/CTrefdnbb76hEn36ucZxlEDGJtfuEzkHI3TlR/udZxmo3eRb8tJeXTLt6Y4P0mEf3rQ5zKVnKYdpIq12Yh8cP/7FiuH6VzecjEwJLi6USl0MHk4esea8ZdqL7CHAadUw6WAaBBg8Q=
