extends: stylelint-config-standard

plugins:
- stylelint-declaration-use-variable

ignoreFiles:
- "src/vendor/**/*"

rules:
  sh-waqar/declaration-use-variable:
  - "/color/"
  - z-index
  - font-size

  selector-pseudo-class-no-unknown:
    - true
    - ignorePseudoClasses:
      - global
      - local
